all:
  hosts:
    localhost:
      ansible_connection: ssh
      ansible_user: zeta
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
  vars:
    apache_port: 8080
    apache_server_name: example.com
    dns_servers:
      - 8.8.8.8
      - 8.8.4.4
    dhcp_subnet: 192.168.1.0
    dhcp_netmask: 255.255.255.0
    dhcp_range_start: 192.168.1.100
    dhcp_range_end: 192.168.1.200
    router_ip: 192.168.1.1
    dns_domain: example.com

